# Nothing matched, assuming buildroot command

CURTARGETFILE := $(WORKSPACE_TOPLEVEL)/current_target
CURTARGET := $(file < $(CURTARGETFILE))

BUILDROOT_ENV_VARS := BR2_EXTERNAL=$(REPO_BUILDROOT_TREE_FULLPATH) \
			BR2_DL_DIR=$(WORKSPACE_TOPLEVEL)/output/dl

BUILDROOT_MAKEFILE_VARS := O=$(WORKSPACE_TOPLEVEL)/output/$(CURTARGET)

BUILDROOT_MAKE := $(BUILDROOT_ENV_VARS) make $(BUILDROOT_MAKEFILE_VARS) -C $(REPO_BUILDROOT_FULLPATH)

BUILDROOT_DEFCONFIG_DIRS := $(REPO_BUILDROOT_FULLPATH)/configs $(REPO_BUILDROOT_TREE_FULLPATH)/configs

BUILDROOT_TARGETS := $(foreach defconfig,\
$(foreach dir,$(BUILDROOT_DEFCONFIG_DIRS),\
$(notdir $(wildcard $(dir)/*_defconfig))),$(patsubst %_defconfig,%,$(defconfig))\
)

$(BUILDROOT_TARGETS):
	$(BUILDROOT_ENV_VARS) make O=$(WORKSPACE_TOPLEVEL)/output/$(@) -C $(REPO_BUILDROOT_FULLPATH) $@_defconfig
	echo $@ >$(CURTARGETFILE)
	$(BUILDROOT_ENV_VARS) make O=$(WORKSPACE_TOPLEVEL)/output/$(@) -C $(REPO_BUILDROOT_FULLPATH) all

%_defconfig:
	$(BUILDROOT_ENV_VARS) make O=$(WORKSPACE_TOPLEVEL)/output/$(*) -C $(REPO_BUILDROOT_FULLPATH) $@
	echo $* >$(CURTARGETFILE)

%:
	$(BUILDROOT_MAKE) $*
